package com.newtoncodes.spellchecker;


public class Hunspell {
    private static String[] dictionaries = {
            "Armenian - Eastern",
            "Armenian - Western",
            "Austrian",
            "Basque",
            "Belgian",
            "Bulgarian",
            "Catalan",
            "Croatian",
            "Czech",
            "Danish",
            "Dutch",
            "English - American",
            "English - Australian",
            "English - British",
            "English - Canadian",
            "English - South African",
            "Estonian",
            "French",
            "Galego",
            "German",
            "Greek",
            "Hungarian",
            "Icelandic",
            "Indonesia",
            "Italian",
            "Korean",
            "Latvian",
            "Lithuanian",
            "Luxembourgish",
            "Malays",
            "Mongolian",
            "Norwegian - Bokmal",
            "Norwegian - Nynorsk",
            "Persian",
            "Polish",
            "Portuguese - Brazilian",
            "Portuguese - European",
            "Romanian",
            "Russian",
            "Serbian - Cyrillic",
            "Serbian - Latin",
            "Slovak",
            "Slovenian",
            "Spanish",
            "Swedish",
            "Swiss",
            "Turkish",
            "Ukrainian",
            "Vietnamese",
    };

    public static String[] getDictionaries() {
        return dictionaries;
    }
}
